---
title: "Principle Component Analysis & Index Construction"
author: "Jill Guerra"
date: "January 5, 2016"
output: 
  html_document:
    keep_md: true 
---
###Load packages 
```{r}
library(ggplot2)
library(car) 
library(dplyr)
suppressPackageStartupMessages(library(dplyr))
library(gridExtra)
library("reshape2")
```

###Import file - Remember to change depending on what you need. 
```{r}
fulldf_aei<- read.csv("~/AEI_Index/Census_data_formatted_for_R_01.06.16.csv", quote = '"', sep = ",", na.strings = c(".",""), strip.white = TRUE) # load full dataset
```

###Principle Component Analysis 
ALL FROM HERE: http://www.r-bloggers.com/computing-and-visualizing-pca-in-r/
```{r}

# omit NAs for this part 
fulldf_aei_omit <- na.omit(fulldf_aei)

# log transform 
log_aei <- log(fulldf_aei_omit [, 3:11]) # columns with the AE components going to be used in the index 
aei_species <- fulldf_aei_omit [, 2] # this calls the categorical variable 
# calls the Municipality names.

#Change all infinite values to NAs 
log_aei<- do.call(data.frame,lapply(log_aei, function(x) replace(x, is.infinite(x),NA))) # this changes all of them! 
# ok but the data.frame doesn't have any other things in there (only the components)

#Drop all observations with NA (thus all the infinite because they were previously changed to NA)
log_aei <- na.omit(log_aei) # shows that it is changed from 262 levels down to 139 levels. 

#Apply PCA - scale. = TRUE is highly advisable, but default is FALSE. 
log_aei_pca <- prcomp(log_aei, 
                      na.action = na.exclude, 
                      center = TRUE,               
                      scale. = TRUE) 
print(log_aei_pca)

# plot method
plot(log_aei_pca, type = "l") # this won't work unless the NAs are omitted a few lines up. 

# summary method
summary(log_aei_pca)

```

### Graphing the PCA 
```{r}
library(devtools)
#install_github("ggbiplot", "vqv") 
 
library(ggbiplot)
plot_pca <- ggbiplot(log_aei_pca, obs.scale = 1, var.scale = 1,
              ellipse = TRUE, 
              circle = TRUE)
# original code for this at group = aei_species - but I had to take it out because there were different number of observations. This is because I had to drop values in the log_aei df as prcomp would not work with NAs. 

plot_pca <- plot_pca + scale_color_discrete(name = '') + 
  theme(legend.direction = 'horizontal', legend.position = 'top')

print(plot_pca)
```

###AEI with brute force 
```{r create AEI with force}
#### randomly chosen variables 
# this works for the regular data.frame 
ae_index <- ((fulldf_aei$nochem + fulldf_aei$usefert +fulldf_aei$orgcomp + fulldf_aei$manure + fulldf_aei$croprot + fulldf_aei$covercrop + fulldf_aei$apm + fulldf_aei$lowtill + fulldf_aei$drip)/9) # create index! 

add_aei_df <- cbind(fulldf_aei, ae_index) # add the index into a new df 
# NAs were not excluded 

```

Drop NA observations when needed
```{r dropNAsindataframe}
#Create a new data.frame that only has rows w/o NAs
add_aei_df_dropnas <- na.omit(fulldf_aei) # 262/293 municipalities included 

```


###Check for scale consistency - Chronbach's alpha
```{r}
#alpha(ae_index)
####### Whaaat? Why is it returning colours? 
```


```{r testing regressions}
lm_test3 <- lm(ae_index ~ offfarminc + credit + lowincome, add_aei_df)

 lm_test3



```

##Resources & Notes 

####PCA 
overview: http://www.r-bloggers.com/computing-and-visualizing-pca-in-r/
cleaning INF values: http://stackoverflow.com/questions/12188509/cleaning-inf-values-from-an-r-dataframe
* can't use is.infinite for a data.frame 